openapi: 3.0.0
info:
  title: Mount Shop
  version: 1.0.0
servers:
  - url: https://mount-shop-be.onrender.com
components:
  securitySchemes:
    noauthAuth:
      type: http
      scheme: noauth
    bearerAuth:
      type: http
      scheme: bearer
security:
  - bearerAuth: []
tags:
  - name: Auth
  - name: Products
  - name: Categories
  - name: Brands
  - name: Carts
  - name: Media
  - name: User
  - name: Comments
  - name: Addresses
  - name: Order
  - name: Dashboard
paths:
  /api/auth/register:
    post:
      tags:
        - Auth
      summary: Register
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                full_name: Nguy·ªÖn VƒÉn ƒê·∫°o
                email: nguyenvandao0307+26@gmail.com
                password: '12345678'
                confirm_password: '12345678'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/auth/login:
    post:
      tags:
        - Auth
      summary: Login
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                email: nguyenvandao0307@gmail.com
                password: '1234567'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/auth/logout:
    post:
      tags:
        - Auth
      summary: Logout
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                refresh_token: '{{refresh_token}}'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/auth/change-password:
    post:
      tags:
        - Auth
      summary: Change Password
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                current_password: '123456'
                new_password: '12345678'
                confirm_password: '12345678'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/auth/forgot-password:
    post:
      tags:
        - Auth
      summary: Forgot Password
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                email: nguyenvandao0307@gmail.com
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/auth/verify-forgot-password:
    post:
      tags:
        - Auth
      summary: Verify Forgot Password
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                forgot_password_token: >-
                  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjozLCJ0b2tlbl90eXBlIjoyLCJ2ZXJpZnkiOiIxIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzU5Njc4ODI5LCJleHAiOjE3NjAyODM2Mjl9.Ugf3lBCwmhkzvu4BA1ydcRVoIA91xMqXZrf-fZsI6CM
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/auth/reset-password:
    post:
      tags:
        - Auth
      summary: Reset Password
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                forgot_password_token: >-
                  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjozLCJ0b2tlbl90eXBlIjoyLCJ2ZXJpZnkiOiIxIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzU5Njc4ODI5LCJleHAiOjE3NjAyODM2Mjl9.Ugf3lBCwmhkzvu4BA1ydcRVoIA91xMqXZrf-fZsI6CM
                password: '12345678'
                confirm_password: '12345678'
      security:
        - noauthAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/auth/verify-email:
    post:
      tags:
        - Auth
      summary: Verify Email
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                email_verify_token: >-
                  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo3LCJ0b2tlbl90eXBlIjozLCJ2ZXJpZnkiOiIwIiwicm9sZSI6ImN1c3RvbWVyIiwiaWF0IjoxNzU5NjUyNzE1LCJleHAiOjE3NjAyNTc1MTV9.bJ-Lo4ahj_5ctVplZGvT0HTDX7cgDvjTy2tAd5od9aA
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/auth/refresh-token:
    post:
      tags:
        - Auth
      summary: Refresh Token
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                refresh_token: '{{refresh_token}}'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/admin/products:
    post:
      tags:
        - Products
      summary: Add Product
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: √Åo Polo C·ªï V D·ªát Kim Cao C·∫•p Phong C√°ch H√†n Qu·ªëc SUGAL TOP 005
                image: >-
                  https://mount-shop-s3.s3.ap-southeast-1.amazonaws.com/images/podtesa344qopavycqlzv5tzd.png
                images:
                  - >-
                    https://mount-shop-s3.s3.ap-southeast-1.amazonaws.com/images/podtesa344qopavycqlzv5tzd.png
                  - >-
                    https://mount-shop-s3.s3.ap-southeast-1.amazonaws.com/images/yiifln8rsizpxd8q2fdvw6fzk.png
                  - >-
                    https://mount-shop-s3.s3.ap-southeast-1.amazonaws.com/images/u2lnicwz2ns6v5ub1zd81b4wx.png
                  - >-
                    https://mount-shop-s3.s3.ap-southeast-1.amazonaws.com/images/vbfdcf17jvq1oswad0d4t05ae.png
                  - >-
                    https://mount-shop-s3.s3.ap-southeast-1.amazonaws.com/images/s1gi39suba29f623hu0hjc0mv.png
                description: >-
                  <p><strong>√Åo Polo C·ªï V D·ªát Kim Cao C·∫•p Phong C√°ch H√†n Qu·ªëc
                  SUGAL TOP 005</strong></p><p>Kh√°m ph√° phong c√°ch th·ªùi trang
                  hi·ªán ƒë·∫°i v·ªõi m·∫´u √°o polo c·ªï V d·ªát kim cao c·∫•p t·ª´ th∆∞∆°ng hi·ªáu
                  <strong>SUGAL</strong>. Thi·∫øt k·∫ø tinh t·∫ø, mang h∆°i h∆∞·ªõng H√†n
                  Qu·ªëc gi√∫p b·∫°n n·ªïi b·∫≠t v√† thanh l·ªãch trong m·ªçi ho√†n
                  c·∫£nh.</p><ul><li>Ch·∫•t li·ªáu: D·ªát kim cao c·∫•p, m·ªÅm m·ªãn, tho√°ng
                  m√°t v√† co gi√£n t·ªët.</li><li>Ki·ªÉu d√°ng: C·ªï V th·ªùi th∆∞·ª£ng, t√¥n
                  d√°ng v√† t·∫°o c·∫£m gi√°c tr·∫ª trung.</li><li>M√†u s·∫Øc: Trung t√≠nh,
                  d·ªÖ ph·ªëi ƒë·ªì, ph√π h·ª£p v·ªõi nhi·ªÅu phong c√°ch.</li><li>·ª®ng d·ª•ng:
                  Ph√π h·ª£p khi ƒëi l√†m, ƒëi ch∆°i, h·∫πn h√≤ hay d·∫°o
                  ph·ªë.</li></ul><p>ƒê∆∞·ªùng may tinh x·∫£o, form √°o chu·∫©n gi√∫p t√¥n
                  l√™n v·∫ª l·ªãch l√£m, t·ª± tin c·ªßa ph√°i m·∫°nh. D·ªÖ d√†ng k·∫øt h·ª£p v·ªõi
                  qu·∫ßn √¢u, qu·∫ßn jeans ho·∫∑c qu·∫ßn short ƒë·ªÉ t·∫°o n√™n phong c√°ch
                  ri√™ng c·ªßa b·∫°n.</p><p><strong>SUGAL TOP 005</strong> ‚Äì l·ª±a ch·ªçn
                  ho√†n h·∫£o cho nh·ªØng ai y√™u th√≠ch s·ª± thanh l·ªãch, hi·ªán ƒë·∫°i v√† ƒë·∫≠m
                  ch·∫•t H√†n Qu·ªëc.</p><hr /><h4>üéØ Cam k·∫øt ch·∫•t
                  l∆∞·ª£ng</h4><ul><li>S·∫£n ph·∫©m 100% gi·ªëng m√¥ t·∫£ v√† h√¨nh
                  ·∫£nh.</li><li>Ch·∫•t li·ªáu cao c·∫•p, ƒë∆∞·ª£c ki·ªÉm tra k·ªπ l∆∞·ª°ng tr∆∞·ªõc
                  khi giao h√†ng.</li><li>ƒê·∫£m b·∫£o h√†ng m·ªõi, nguy√™n tem nh√£n, ch∆∞a
                  qua s·ª≠ d·ª•ng.</li></ul><h4>üîÅ Ch√≠nh s√°ch ƒë·ªïi tr·∫£</h4><ul><li>H·ªó
                  tr·ª£ ƒë·ªïi tr·∫£ trong v√≤ng <strong>7 ng√†y</strong> k·ªÉ t·ª´ khi nh·∫≠n
                  h√†ng.</li><li>√Åp d·ª•ng v·ªõi s·∫£n ph·∫©m c√≤n nguy√™n tag, ch∆∞a gi·∫∑t
                  ho·∫∑c qua s·ª≠ d·ª•ng.</li><li>N·∫øu s·∫£n ph·∫©m l·ªói t·ª´ nh√† s·∫£n xu·∫•t,
                  ch√∫ng t√¥i s·∫Ω <strong>ƒë·ªïi m·ªõi 100%</strong>.</li><li>Kh√°ch h√†ng
                  vui l√≤ng quay video khi m·ªü h√†ng ƒë·ªÉ ƒë∆∞·ª£c h·ªó tr·ª£ t·ªët
                  nh·∫•t.</li></ul><p><em>C·∫£m ∆°n b·∫°n ƒë√£ tin t∆∞·ªüng l·ª±a ch·ªçn s·∫£n
                  ph·∫©m c·ªßa <strong>SUGAL</strong>. Ch√∫ng t√¥i lu√¥n n·ªó l·ª±c mang
                  ƒë·∫øn cho b·∫°n tr·∫£i nghi·ªám mua s·∫Øm h√†i l√≤ng nh·∫•t!</em></p>
                price_before_discount: 240000
                price: 169000
                rating: '4.0'
                sold: 200
                stock: 121
                category_id: '7'
                brand_id: '17'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/admin/products/8:
    put:
      tags:
        - Products
      summary: Update Product
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: √Åo Polo C·ªï V D·ªát Kim Cao C·∫•p Phong C√°ch H√†n Qu·ªëc SUGAL TOP 005
                image: >-
                  https://mount-shop-s3.s3.ap-southeast-1.amazonaws.com/images/podtesa344qopavycqlzv5tzd.png
                images:
                  - >-
                    https://mount-shop-s3.s3.ap-southeast-1.amazonaws.com/images/podtesa344qopavycqlzv5tzd.png
                  - >-
                    https://mount-shop-s3.s3.ap-southeast-1.amazonaws.com/images/yiifln8rsizpxd8q2fdvw6fzk.png
                  - >-
                    https://mount-shop-s3.s3.ap-southeast-1.amazonaws.com/images/u2lnicwz2ns6v5ub1zd81b4wx.png
                  - >-
                    https://mount-shop-s3.s3.ap-southeast-1.amazonaws.com/images/vbfdcf17jvq1oswad0d4t05ae.png
                  - >-
                    https://mount-shop-s3.s3.ap-southeast-1.amazonaws.com/images/s1gi39suba29f623hu0hjc0mv.png
                description: >-
                  <p><strong>√Åo Polo C·ªï V D·ªát Kim Cao C·∫•p Phong C√°ch H√†n Qu·ªëc
                  SUGAL TOP 005</strong></p><p>Kh√°m ph√° phong c√°ch th·ªùi trang
                  hi·ªán ƒë·∫°i v·ªõi m·∫´u √°o polo c·ªï V d·ªát kim cao c·∫•p t·ª´ th∆∞∆°ng hi·ªáu
                  <strong>SUGAL</strong>. Thi·∫øt k·∫ø tinh t·∫ø, mang h∆°i h∆∞·ªõng H√†n
                  Qu·ªëc gi√∫p b·∫°n n·ªïi b·∫≠t v√† thanh l·ªãch trong m·ªçi ho√†n
                  c·∫£nh.</p><ul><li>Ch·∫•t li·ªáu: D·ªát kim cao c·∫•p, m·ªÅm m·ªãn, tho√°ng
                  m√°t v√† co gi√£n t·ªët.</li><li>Ki·ªÉu d√°ng: C·ªï V th·ªùi th∆∞·ª£ng, t√¥n
                  d√°ng v√† t·∫°o c·∫£m gi√°c tr·∫ª trung.</li><li>M√†u s·∫Øc: Trung t√≠nh,
                  d·ªÖ ph·ªëi ƒë·ªì, ph√π h·ª£p v·ªõi nhi·ªÅu phong c√°ch.</li><li>·ª®ng d·ª•ng:
                  Ph√π h·ª£p khi ƒëi l√†m, ƒëi ch∆°i, h·∫πn h√≤ hay d·∫°o
                  ph·ªë.</li></ul><p>ƒê∆∞·ªùng may tinh x·∫£o, form √°o chu·∫©n gi√∫p t√¥n
                  l√™n v·∫ª l·ªãch l√£m, t·ª± tin c·ªßa ph√°i m·∫°nh. D·ªÖ d√†ng k·∫øt h·ª£p v·ªõi
                  qu·∫ßn √¢u, qu·∫ßn jeans ho·∫∑c qu·∫ßn short ƒë·ªÉ t·∫°o n√™n phong c√°ch
                  ri√™ng c·ªßa b·∫°n.</p><p><strong>SUGAL TOP 005</strong> ‚Äì l·ª±a ch·ªçn
                  ho√†n h·∫£o cho nh·ªØng ai y√™u th√≠ch s·ª± thanh l·ªãch, hi·ªán ƒë·∫°i v√† ƒë·∫≠m
                  ch·∫•t H√†n Qu·ªëc.</p><hr /><h4>üéØ Cam k·∫øt ch·∫•t
                  l∆∞·ª£ng</h4><ul><li>S·∫£n ph·∫©m 100% gi·ªëng m√¥ t·∫£ v√† h√¨nh
                  ·∫£nh.</li><li>Ch·∫•t li·ªáu cao c·∫•p, ƒë∆∞·ª£c ki·ªÉm tra k·ªπ l∆∞·ª°ng tr∆∞·ªõc
                  khi giao h√†ng.</li><li>ƒê·∫£m b·∫£o h√†ng m·ªõi, nguy√™n tem nh√£n, ch∆∞a
                  qua s·ª≠ d·ª•ng.</li></ul><h4>üîÅ Ch√≠nh s√°ch ƒë·ªïi tr·∫£</h4><ul><li>H·ªó
                  tr·ª£ ƒë·ªïi tr·∫£ trong v√≤ng <strong>7 ng√†y</strong> k·ªÉ t·ª´ khi nh·∫≠n
                  h√†ng.</li><li>√Åp d·ª•ng v·ªõi s·∫£n ph·∫©m c√≤n nguy√™n tag, ch∆∞a gi·∫∑t
                  ho·∫∑c qua s·ª≠ d·ª•ng.</li><li>N·∫øu s·∫£n ph·∫©m l·ªói t·ª´ nh√† s·∫£n xu·∫•t,
                  ch√∫ng t√¥i s·∫Ω <strong>ƒë·ªïi m·ªõi 100%</strong>.</li><li>Kh√°ch h√†ng
                  vui l√≤ng quay video khi m·ªü h√†ng ƒë·ªÉ ƒë∆∞·ª£c h·ªó tr·ª£ t·ªët
                  nh·∫•t.</li></ul><p><em>C·∫£m ∆°n b·∫°n ƒë√£ tin t∆∞·ªüng l·ª±a ch·ªçn s·∫£n
                  ph·∫©m c·ªßa <strong>SUGAL</strong>. Ch√∫ng t√¥i lu√¥n n·ªó l·ª±c mang
                  ƒë·∫øn cho b·∫°n tr·∫£i nghi·ªám mua s·∫Øm h√†i l√≤ng nh·∫•t!</em></p>
                price_before_discount: 169000
                price: 249000
                rating: '4.0'
                sold: 200
                stock: 121
                category_id: '7'
                brand_id: '17'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/admin/products/5:
    delete:
      tags:
        - Products
      summary: Delete Product
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/products/268:
    get:
      tags:
        - Products
      summary: Get Product
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/products:
    get:
      tags:
        - Products
      summary: Get Products
      parameters:
        - name: page
          in: query
          schema:
            type: integer
          example: '2'
        - name: limit
          in: query
          schema:
            type: integer
          example: '15'
        - name: category
          in: query
          schema:
            type: string
        - name: brands
          in: query
          schema:
            type: string
        - name: search
          in: query
          schema:
            type: string
          example: B·ªô
        - name: min_price
          in: query
          schema:
            type: string
        - name: max_price
          in: query
          schema:
            type: string
        - name: rating
          in: query
          schema:
            type: string
        - name: order
          in: query
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/admin/categories:
    post:
      tags:
        - Categories
      summary: Add Category
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: ƒê·ªìng h·ªì
                image: >-
                  https://mount-shop-s3.s3.ap-southeast-1.amazonaws.com/images/ad62a0dowi8orce8g95zlyxra.png
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/admin/categories/15:
    put:
      tags:
        - Categories
      summary: Update Category
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: M∆∞a
                image: >-
                  https://mount-shop-s3.s3.ap-southeast-1.amazonaws.com/images/on98ijx2s1x3b7efgrsd6bsbe.png
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/admin/categories/2:
    delete:
      tags:
        - Categories
      summary: Delete Category
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/admin/categories/4:
    get:
      tags:
        - Categories
      summary: Get Category
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/categories/3/brands:
    get:
      tags:
        - Categories
      summary: Get Brands By Category Id
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/categories:
    get:
      tags:
        - Categories
      summary: Get Categories
      parameters:
        - name: page
          in: query
          schema:
            type: integer
          example: '1'
        - name: limit
          in: query
          schema:
            type: integer
          example: '15'
        - name: search
          in: query
          schema:
            type: string
          example: ƒê·ªìng H·ªì
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/admin/brands:
    post:
      tags:
        - Brands
      summary: Add Brand
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: Rolex
                image: >-
                  https://mount-shop-s3.s3.ap-southeast-1.amazonaws.com/images/meiq11g0s90pvd4h6s95kq3mc.png
                category_id: '12'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - Brands
      summary: Get Brands
      parameters:
        - name: page
          in: query
          schema:
            type: integer
          example: '1'
        - name: limit
          in: query
          schema:
            type: integer
          example: '15'
        - name: search
          in: query
          schema:
            type: string
          example: LG
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/admin/brands/1:
    put:
      tags:
        - Brands
      summary: Update Brand
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: SamSung
                image: >-
                  https://mount-shop-s3.s3.ap-southeast-1.amazonaws.com/images/odeupcfw84ba3aaj9234upytw.png
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - Brands
      summary: Delele Brand
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/admin/brands/3:
    get:
      tags:
        - Brands
      summary: Get Brand
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/user/carts:
    post:
      tags:
        - Carts
      summary: Add Cart
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                product_id: 17
                quantity: 1
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - Carts
      summary: Get Carts
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/user/carts/1:
    delete:
      tags:
        - Carts
      summary: Delete Cart
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/user/carts/3:
    put:
      tags:
        - Carts
      summary: Update Cart
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                quantity: 2
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/media/upload-image:
    post:
      tags:
        - Media
      summary: Upload Image
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                image:
                  type: string
                  format: binary
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/user/profile:
    get:
      tags:
        - User
      summary: Get Profile
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    put:
      tags:
        - User
      summary: Update Profile
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                avatar: ''
                full_name: VƒÉn ƒê·∫°o
                phone: '0985732825'
                address: Kho√°i Ch√¢u - H∆∞ng Y√™n
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/admin/users:
    get:
      tags:
        - User
      summary: Get Users
      parameters:
        - name: page
          in: query
          schema:
            type: integer
          example: '1'
        - name: limit
          in: query
          schema:
            type: integer
          example: '15'
        - name: search
          in: query
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    put:
      tags:
        - User
      summary: Update User Role
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                user_id: '39'
                role_id: '2'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/admin/users/38:
    delete:
      tags:
        - User
      summary: Delete User
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/user/comments:
    post:
      tags:
        - Comments
      summary: Add Comment
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                product_id: 24
                content: TV ƒë·∫πp qu√° b·∫°n !!!
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/user/comments/1:
    delete:
      tags:
        - Comments
      summary: Delete Comment
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/comments/61:
    get:
      tags:
        - Comments
      summary: Get Comment Product
      parameters:
        - name: page
          in: query
          schema:
            type: integer
          example: '1'
        - name: limit
          in: query
          schema:
            type: integer
          example: '15'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/admin/comments:
    get:
      tags:
        - Comments
      summary: Get Comments All
      parameters:
        - name: page
          in: query
          schema:
            type: integer
          example: '1'
        - name: limit
          in: query
          schema:
            type: integer
          example: '15'
        - name: search
          in: query
          schema:
            type: string
          example: ƒê·ªìng
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/user/addresses:
    post:
      tags:
        - Addresses
      summary: Add Address
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                full_name: Tr·∫ßn Th·ªã Mai
                phone: '0988877722'
                address: Ph∆∞·ªùng D·ªãch V·ªçng, Qu·∫≠n C·∫ßu Gi·∫•y, H√† N·ªôi
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - Addresses
      summary: Get Addresses
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/user/orders:
    post:
      tags:
        - Order
      summary: Add Order
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                total_price: 202000
                address_id: 49
                cart_ids:
                  - 34
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - Order
      summary: Get Orders
      parameters:
        - name: page
          in: query
          schema:
            type: integer
          example: '1'
        - name: limit
          in: query
          schema:
            type: integer
          example: '15'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/user/orders/3:
    get:
      tags:
        - Order
      summary: Get Oder Detail
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/user/orders/21:
    put:
      tags:
        - Order
      summary: Update Order Cancel
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                status: cancelled
                cancel_reason: T√¥i mu·ªën ƒë·ªïi s·∫£n ph·∫©m kh√°c
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/admin/orders:
    get:
      tags:
        - Order
      summary: Get Orders All
      parameters:
        - name: page
          in: query
          schema:
            type: integer
          example: '1'
        - name: limit
          in: query
          schema:
            type: integer
          example: '15'
        - name: search
          in: query
          schema:
            type: string
        - name: status
          in: query
          schema:
            type: string
          example: delivered
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/admin/orders/15:
    put:
      tags:
        - Order
      summary: Update Order
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                status: delivered
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/admin/dashboard:
    get:
      tags:
        - Dashboard
      summary: DashBoard
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
